# Generated by Django 4.2.4 on 2023-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriDataAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
    ]
